executor:
  name: nodejs
  options:
    entry: main.ts
inputs_def:
  - handle: input
    json_schema:
      {}
outputs_def:
  - handle: output
    json_schema:
      {}
title: additional-block
additional_inputs: true
additional_outputs: true
