name: test in layer
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.filter.outputs.should_skip }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: leavesster/pull-request-path-filter@v0.2
        id: "filter"
        with:
          paths: |
            - "packages/oocana/**"
            - "flow-examples/test/layer**"
            - "flow-examples/flows**"
            - "flow-examples/subflows**"
            - "flow-examples/packages**"
            - ".github/workflows/layer.yml"

  linux:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    needs: [skip]
    if: ${{ needs.skip.outputs.should_skip != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - id: rootfs
        run: |-
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            echo "architecture=amd64" >> $GITHUB_OUTPUT
          else
            echo "architecture=arm64" >> $GITHUB_OUTPUT
          fi
      - uses: ./.github/actions/ovmlayer
        with:
          rootfs: https://github.com/oomol/ovmlayer-rootfs/releases/download/base-rootfs%400.3.0/${{steps.rootfs.outputs.architecture}}-rootfs.tar
          token: ${{ secrets.ACCESS_REPO }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm run build
      - name: test layer api
        run: |
          cd flow-examples
          pnpm run layer
      - name: modify overlayfs # https://github.com/oomol/ovmlayer/issues/25
        run: |
          sudo bash -c 'echo N > /sys/module/overlay/parameters/redirect_always_follow'
          sudo bash -c 'echo N > /sys/module/overlay/parameters/redirect_dir'
          sudo bash -c 'echo N > /sys/module/overlay/parameters/xino_auto'
          sudo bash -c 'echo N > /sys/module/overlay/parameters/metacopy'
          sudo bash -c 'echo N > /sys/module/overlay/parameters/check_copy_up'
          sudo bash -c 'echo N > /sys/module/overlay/parameters/index'
      - name: add executor to rootfs layers
        run: |
          node ./layer.mjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: test flow on layer
        run: |
          pnpm run broker &
          sleep 5
          cd flow-examples
          pnpm run test
      - name: upload logs
        uses: actions/upload-artifact@v4
        with:
          name: oocana-logs
          path: |
            ~/.oocana/sessions/
            /tmp/ovmlayer.log
          retention-days: 1
        if: failure()
