name: "setup oocana-node action"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/oocana-node.yml"
      - ".github/actions/oocana-node/**"
      - "executor.sh"
      - "install-node.sh"
      - "layer.mjs"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  action-test:
    runs-on: ubuntu-latest
    env:
      OVMLAYER_LOG: /tmp/ovmlayer.log
      OVMLAYER_REPOSITORY: ${{ vars.OVMLAYER_REPOSITORY || 'ovmlayer-next' }}
      OVMLAYER_USE_RUNTIME_SETUP: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Generate GitHub App Token for oomol/${{ env.OVMLAYER_REPOSITORY }}
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.OOMOL_DOWNLOADER_APP_ID }}
          private-key: ${{ secrets.OOMOL_DOWNLOADER_APP_PRIVATE_KEY }}
          owner: oomol
          repositories: ${{ env.OVMLAYER_REPOSITORY }}
      - uses: oomol/oocana-rust/.github/actions/ovmlayer@6c365c646efde55d6c4636b5921e237020ea2838
        with:
          repository: ${{ env.OVMLAYER_REPOSITORY }}
          rootfs: https://github.com/oomol/ovmlayer-rootfs/releases/download/base-rootfs%400.3.0/amd64-rootfs.tar
          token: ${{ steps.app-token.outputs.token }}
          use-runtime-setup: ${{ env.OVMLAYER_USE_RUNTIME_SETUP }}
      - name: setup oocana-node action without layer
        uses: ./.github/actions/oocana-node
        with:
          ref: ${{ github.sha }}
          path: "oocana-node"
      - name: setup oocana-node action with layer
        uses: ./.github/actions/oocana-node
        with:
          ref: ${{ github.sha }}
          create-layer: "true"
          path: "oocana-node"
      - name: upload log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ovmlayer-log
          path: /tmp/ovmlayer.log
