name: pr
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  UST_BACKTRACE: full

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.filter.outputs.should_skip }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: leavesster/pull-request-path-filter@v0.2
        id: "filter"
        with:
          paths: |
            - "**"
            - "!.github/**"
            - "!.vscode/**"
            - "!**.md"
            - ".github/workflows/pr.yml"

  check:
    runs-on: ubuntu-latest
    needs: [skip]
    if: ${{ needs.skip.outputs.should_skip != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: install
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm run build
      - name: check
        run: pnpm run ts-check
      - name: test flow and other oocana api
        timeout-minutes: 8
        run: |
          pnpm run broker &
          sleep 5
          pnpm run -F oocana-test nonlayer
          pnpm run test
